### ISSUE TITLE
[Bug]: file-loader seems to be required as a peer dependency

### ISSUE THREAD

**Issue by ErreMalote** [web-infra-dev/rsbuild#1238]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 667.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 120.1.61.114
    Chrome: 120.0.6099.109
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-node-polyfill: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-react: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-svgr: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-type-check: ^0.3.0 => 0.3.0
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/8674348/ee6cd17c-c7b7-48c4-bb76-61ff52965d2d)

### Reproduce link

*

### Reproduce Steps

1. install rs-build 0.3.0
2. install @rsbuild/plugin-react, @rsbuild/plugin-svgr, and @rsbuild/plugin-node-polyfill
3. build a project that has svgs

**Comment by ErreMalote** [comment]
the issue resolves when I manually install `file-loader`

**Comment by chenjiahan** [comment]
We will fix it today 😄

**Comment by denniscual** [comment]
[file-loader](https://v4.webpack.js.org/loaders/file-loader/) is added as `devDependencies`. Due to this, when running dev server or build while importing svg, it throws the below error:

<img width="1318" alt="Screenshot 2024-05-06 at 9 07 06 PM" src="https://github.com/web-infra-dev/rsbuild/assets/17754712/6d46a561-8831-44e8-8726-a0364141fd9c"> .

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/rsbuild/pull/2273, I will release a new version soon
