### ISSUE TITLE
[Bug]: 打包上线出现编译错误

### ISSUE THREAD

**Issue by Xgj22** [web-infra-dev/rsbuild#1247]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 29.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.0
  npmPackages:
    @rsbuild/core: ^0.2.18 => 0.2.18 
    @rsbuild/plugin-node-polyfill: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-stylus: ^0.3.0 => 0.3.0 
    @rsbuild/plugin-vue2: ^0.3.0 => 0.3.0
```

### Details

本地运行没问题，打包上线出现编译错误
Failed to compile, check the errors for troubleshooting.
Module Error
  × ParseError: expected "}", got ":"
  │     at Parser.error (/Users/xgj/Desktop/workspace/hll-mdap-crash-web/node_modules/@rsbuild/plugin-stylus/node_modules/stylus/lib/parser.js:262:11)
  │     at Parser.expect (/Users/xgj/Desktop/workspace/hll-mdap-crash-web/node_modules/@rsbuild/plugin-stylus/node_modules/stylus/lib/parser.js:290:12)
  │     at Parser.interpolate (/Users/xgj/Desktop/workspace/hll-mdap-crash-web/node_modules/@rsbuild/plugin-stylus/node_modules/stylus/lib/parser.js:1566:14)
  │     at Parser.property (/Users/xgj/Desktop/workspace/hll-mdap-crash-web/node_modules/@rsbuild/plugin-stylus/node_modules/stylus/lib/parser.js:1589:22)

### Reproduce link

null

### Reproduce Steps

yarn build

**Comment by chenjiahan** [comment]
可以检查下 stylus 代码语法是否有错误，或者提供一个可重现问题的仓库哈

**Comment by chenjiahan** [comment]
As the issue was labeled with `need reproduce`, but no response in 3 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions. For background, please refer to [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

由于该 issue 被标记为 "需要重现"，但在 3 天内没有回应，因此该 issue 将被关闭。如果你有任何进一步的问题，请随时发表评论并重新打开该 issue。背景请参考 [为什么需要最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)。
