### ISSUE TITLE
[Feature]: Support Vue JSX HMR

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#153]
### What problem does this feature solve?

Support Vue JSX HMR.

### What does the proposed API look like?

- https://www.npmjs.com/package/@ant-design-vue/vue-jsx-hot-loader
- https://www.npmjs.com/package/unplugin-vue-jsx-hmr
- https://www.npmjs.com/package/@vitejs/plugin-vue-jsx

**Comment by liyincode** [comment]
Hi! First off, I would like to express my gratitude as the migration of our project from vue-cli to rsbuild has significantly improved our start-up and build performance!

I tried to implement the HMR functionality of plugin-vue-jsx in rsbuild, and referred to the code of @vite/plugin-vue-jsx for inspiration to achieve its functionality.you can find the code here:  [plugin-vue-jsx implementation](https://github.com/liyincode/rsbuild/blob/feat/vue-jsx-hmr/packages/plugin-vue-jsx/src/index.ts)

**Comment by liyincode** [comment]
Hello, rsbuild team! First off, I would like to express my gratitude as the migration of our project from vue-cli to rsbuild has significantly improved our start-up and build performance!

I tried to implement the HMR functionality of plugin-vue-jsx in rsbuild, and referred to the code of @vite/plugin-vue-jsx for inspiration to achieve its functionality. 

code: [plugin-vue-jsx implementation](https://github.com/liyincode/rsbuild/blob/feat/vue-jsx-hmr/packages/plugin-vue-jsx/src/index.ts)

I created a sample code similar to @vite/plugin-vue-jsx and it is able to achieve the same hmr functionality, proving that it can be used normally.

Demo code:[rsbuild HMR demo](https://github.com/liyincode/rsbuild/blob/feat%2Fvue-jsx-hmr/e2e/cases/vue/jsx-hmr/src/index.jsx)

However, when I tried to write a test case using playwright for testing similar to @vite/plugin-vue-jsx, I found that it did not run well. I encountered the following two problems and hope to get your help.

Test code: [Playwright test case](https://github.com/liyincode/rsbuild/blob/feat/vue-jsx-hmr/e2e/cases/vue/jsx-hmr/index.test.ts)

#### 1. React is not defined

[Test code](https://github.com/liyincode/rsbuild/blob/bd6da639485c8079afd32dae21a5e4bde8fec112/e2e/cases/vue/jsx-hmr/index.test.ts#L6)

Running the test with the command `npx playwright test cases/vue/jsx-hmr/index.test.ts` yields a "React is not defined" error. I've authored a custom loader to handle .jsx|.tsx files, but this issue wasn't present in earlier versions of your project. Here's the before and after modification in my code:

[before](https://github.com/web-infra-dev/rsbuild/blob/91527fab9a1d93a79a5da496abfc31363152d780/packages/plugin-vue-jsx/src/index.ts#L19)

```ts
modifyBabelLoaderOptions({
          chain,
          CHAIN_ID,
          modifier: (babelOptions) => {
            babelOptions.plugins ??= [];
            babelOptions.plugins.push([
              require.resolve('@vue/babel-plugin-jsx'),
              options.vueJsxOptions || {}
            ]);
            return babelOptions;
          }
        })
```

after

```ts
      chain.module
          .rule('vue-jsx')
          .test(/\.(jsx|tsx)(\.js)?$/)
          .use('vue-jsx')
          .loader(path.resolve(__dirname, './loader'))
          .options(options.vueJsxOptions ?? {});
```

I troubleshooted and found that if I follow the code below I don't have this problem

```ts
      const rule = chain.module.rule('babel-js');
        if (rule.uses.has('babel')) {
          rule.use('babel').tap((babelOptions) => {
            babelOptions.plugins ??= [];
            babelOptions.plugins.push([
              require.resolve('@vue/babel-plugin-jsx'),
              options.vueJsxOptions || {},
            ]);
            return babelOptions;
          });
        }

        chain.module
          .rule('vue-jsx')
          .test(/\.(jsx|tsx)(\.js)?$/)
          .use('vue-jsx')
          .loader(path.resolve(__dirname, './loader'))
          .options(options.vueJsxOptions ?? {});
      });
```

I am thinking why this issue occurred. It's necessary to push the @vue/babel-plugin-jsx plugin into the rule named babel-js in order for it to function properly. I guess that the code has been processed by @rsbuild/plugin-babel before reaching my loader.

I that @rsbuild/plugin-babel first uses swc and then babel for parsing, but I don't know if there's any connection with this.

However, I don't know how to solve this problem because it seems very redundant. I hope that only one loader can handle both parsing vue-jsx and HMR functionalities at the same time.

#### 2. Lack of HMR updates in Playwright tests

[Test code](https://github.com/liyincode/rsbuild/blob/bd6da639485c8079afd32dae21a5e4bde8fec112/e2e/cases/vue/jsx-hmr/index.test.ts#L47)

In my Playwright tests, after modifying the code, the changes do not reflect on the webpage, preventing further testing. For HMR testing, I need to edit the file code and wait for rsbuild to sync the new code to the browser, but the sync doesn't happen even though local files are updated. I'm unsure how to configure rsbuild to test HMR with Playwright effectively.



The above is the issue I encountered during testing in playwright, but it works fine in the demo. I don't know why this happened and hope to get your help. Thank you!

**Comment by chenjiahan** [comment]
Thank you for your detailed introduction ❤️, I will try to reproduce this problem soon

**Comment by 9aoy** [comment]
About question 2 `Lack of HMR updates in Playwright tests`:

if you want to test HMR, maybe you should run `dev` instead of `build`.

![image](https://github.com/web-infra-dev/rsbuild/assets/22373761/3cd3770b-7035-40bd-8ccc-8fe5067ea206)

**Comment by chenjiahan** [comment]
Sorry I can not reproduce the `React is not defined` issue.

These are the steps I take:

- clone the repo and switch to `feat/vue-jsx-hmr`
- enable the commented code:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/ba83d27a-eb9f-4809-b4fc-c8e6c4299797)

3. run `npx playwright test cases/vue/jsx-hmr/index.test.ts`, I get this:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/f15d2647-692f-4af4-939b-becb8f8827bd)

Maybe there is something wrong with my steps?

**Comment by liyincode** [comment]
@9aoy Thank you very much, it is indeed the case, build is production mode and dev is development mode

**Comment by liyincode** [comment]
@chenjiahan thank reply, You need to comment as follows:

<img width="1075" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/25540709/129ee66e-784e-49e7-bbd1-78f4be7f2014">

beacuse , Lines 21 - 44 of code are two solutions to this problem

**Comment by liyincode** [comment]
@chenjiahan I'm sorry, I didn't finish. Then enter `npx playwright test cases/vue/jsx-hmr/index.test.ts --ui` to open the interface mode, and you can see it in the Console Tab.
<img width="1280" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/25540709/5f25318b-8b42-4435-984f-c45a5d024886">

**Comment by chenjiahan** [comment]
> You need to comment as follows

The `modifyBabelLoaderOptions` should not be replaced with a new rule. This is because the order of custom rules is after the default SWC rule, which means that the JSX in the code was compiled by SWC and cannot be processed by custom rules.

It is recommended to use `modifyBabelLoaderOptions` to apply extra babel plugins.

**Comment by liyincode** [comment]
> > You need to comment as follows
> 
> The `modifyBabelLoaderOptions` should not be replaced with a new rule. This is because the order of custom rules is after the default SWC rule, which means that the JSX in the code was compiled by SWC and cannot be processed by custom rules.
> 
> It is recommended to use `modifyBabelLoaderOptions` to apply extra babel plugins.

Okay, do you mean creating a separate babel plugin for the jsx hmr and adding it to the plugin via the `modifyBabelLoaderOptions` method?

**Comment by chenjiahan** [comment]
Yeah that will be nice

**Comment by liyincode** [comment]
Hi, I've converted the previous `Webpack Loader` form into a `Babel Plugin` form, and it meets most use cases.

Code list:

Babel Plugin: [babel-plugin-vue-jsx-hmr](https://github.com/liyincode/rsbuild/blob/feat%2Fvue-jsx-hmr/packages/plugin-vue-jsx/src/babel-plugin-vue-jsx-hmr.ts)
Case Demo: [vue-jsx-hmr-case](https://github.com/liyincode/rsbuild/blob/feat%2Fvue-jsx-hmr/e2e/cases/vue/jsx-hmr/src/index.jsx) (You can preview this demo by running `npm run dev`)
E2E Test: [vue-jsx-hmr-test](https://github.com/liyincode/rsbuild/blob/feat%2Fvue-jsx-hmr/e2e/cases/vue/jsx-hmr/index.test.ts) (Referenced from [vite-plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/playground/vue-jsx/__tests__/vue-jsx.spec.ts))

This plugin satisfies most of the unit tests, but there are two types it cannot meet, which I can't solve at the moment and need your help with.

### 1. Single .vue files containing only <script lang="jsx"> cannot be hot-reloaded [(unit test)](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/e2e/cases/vue/jsx-hmr/index.test.ts#L173).
**Code Example**:

[mian.jsx](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/e2e/cases/vue/jsx-hmr/src/index.jsx#L16) (You can comment out the other codes, I have already removed them for a better reading experience.)

```
import { createApp } from 'vue';  
import JsxScript from './Script.vue';  
  
function App() {  
  return (  
    <>  
      <JsxScript />          
    </>  
  );  
}  
  
createApp(App).mount('#root');
```
[Script.vue](https://github.com/liyincode/rsbuild/blob/6863223/e2e/cases/vue/jsx-hmr/src/Script.vue)
```
<script lang="jsx">
import { defineComponent, ref } from 'vue'

export default defineComponent(() => {
  const count = ref(4)
  const inc = () => count.value++

  return () => (
    <button class="script" onClick={inc}>
      script {count.value}
    </button>
  )
})
</script>
```
**Steps**:

1. `npm run dev`
2. edit the code in Script.vue, change `script {count.value}` to `script updated {count.value}`, and save.

**Results**:

1. after waiting for the hot update, the expected display on the page is `script updated 4`, but no change occurs.
2. the page renders the modified content only after I manually refresh the browser.

**Troubleshooting**:

1.In the Network Tab of Chrome Developer Tools, you can see that `index.xxx.hot-update.js` is successfully fetched and returns the updated content.
<img width="1733" alt="Pasted image 20240327180719" src="https://github.com/web-infra-dev/rsbuild/assets/25540709/c2939df7-614a-4f56-9075-b60cc552df64">

### 2. Single .vue files that include `<script src="xxx.jsx"></script>` cannot be hot-reloaded.
**Code Example**:

[mian.jsx](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/e2e/cases/vue/jsx-hmr/src/index.jsx#L16)
```
import { createApp } from 'vue';  
import JsxSrcImport from './SrcImport.vue';  
  
function App() {  
  return (  
    <>  
      <JsxSrcImport />  
    </>  
  );  
}  
  
createApp(App).mount('#root');
```
[SrcImport.vue](https://github.com/liyincode/rsbuild/blob/6863223/e2e/cases/vue/jsx-hmr/src/SrcImport.vue)
```
<script src="./SrcImport.jsx"></script>
```
[SrcImport.jsx](https://github.com/liyincode/rsbuild/blob/6863223/e2e/cases/vue/jsx-hmr/src/SrcImport.jsx)
```
import { defineComponent, ref } from 'vue';  
  
export default defineComponent(() => {  
  const count = ref(5);  
  const inc = () => count.value++;  
  
  return () => (  
    <button class="src-import" onClick={inc}>  
      src import {count.value}  
    </button>  );  
});
```
**Steps**:

1. `npm run dev`
2. edit the code in Script.vue, change `src import {count.value}` to `src import updated {count.value}`, and save.

**Results**:

1. after waiting for the hot update, the expected display on the page is `src import updated 5`, but no change occurs.
2. the page renders the modified content only after I manually refresh the browser.

**Troubleshooting**:

1.In the Network Tab of Chrome Developer Tools, you can see that `index.xxx.hot-update.js` is successfully fetched and returns the updated content.
<img width="1663" alt="Pasted image 20240327182043" src="https://github.com/web-infra-dev/rsbuild/assets/25540709/11c1e665-385b-488d-80b9-f82ae23e519d">

If I comment out `babel-plugin-vue-jsx-hmr` and only leave `@vue/babel-plugin-jsx` as before, the above two examples work normally.
```
modifyBabelLoaderOptions({  
  chain,  
  CHAIN_ID,  
  modifier: (babelOptions) => {  
    babelOptions.plugins ??= [];  
    babelOptions.plugins.push(  
      [  
        require.resolve('@vue/babel-plugin-jsx'),  
        options.vueJsxOptions || {},  
      ],  
      // [path.resolve(__dirname, './babel-plugin-vue-jsx-hmr')],  
    );  
    return babelOptions;  
  },  
});
```

## Besides the issues mentioned, there are two requirements when using this setup:

### 1. It is necessary to disable the Babel cache [disable babel cache](https://rsbuild.dev/plugins/list/plugin-babel#compilation-cache).
[rsbuild.config.ts](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/e2e/cases/vue/jsx-hmr/rsbuild.config.ts#L16)
```
  performance: {
    buildCache: false,
  },
```
The principle of this vue-jsx-hmr-babel-plugin is that each time the current file is compiled, it first collects the vue components that need HMR through a [visitor](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/packages/plugin-vue-jsx/src/babel-plugin-vue-jsx-hmr.ts#L21), saving them as [hotComponents](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/packages/plugin-vue-jsx/src/babel-plugin-vue-jsx-hmr.ts#L18). Finally, in the [post](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/packages/plugin-vue-jsx/src/babel-plugin-vue-jsx-hmr.ts#L96) hook function, it appends the associated vue hmr code to the end of the file. Then, at the beginning of compiling the next file, it clears this data in the [pre](https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/packages/plugin-vue-jsx/src/babel-plugin-vue-jsx-hmr.ts#L90) function.

However, if the babel compilation cache is enabled, the hotComponents and other record data cannot be cleared after each execution of this plugin. This causes the next file to compile and erroneously include the previous file's HMR code, leading to runtime errors.

### 2. The Babel Plugin must include files with `.jsx.js` or `.tsx.js` extensions.
(rsbuild.config.ts)[https://github.com/liyincode/rsbuild/blob/686322333e2cae557b101ee6e6778f804959163c/e2e/cases/vue/jsx-hmr/rsbuild.config.ts#L10]
```
plugins: [
    pluginVue(),
    pluginBabel({
      include: /\.(?:jsx|tsx)(\.js)?$/,
      exclude: /[\\/]node_modules[\\/]/,
    }),
    pluginVueJsx(),
  ],
```
This is because files of the type [SrcImport.vue](https://github.com/liyincode/rsbuild/blob/6863223/e2e/cases/vue/jsx-hmr/src/SrcImport.vue) are first compiled into files with a jsx.js extension. Then, they are processed by `@vue/babel-plugin-jsx`.

**Comment by chenjiahan** [comment]
Thank you for your great work!

Among the several issues mentioned above, the first two problems do not seem to be the main use cases. We can create separate issues for them and consider how to support them.

For the issue of buildCache, disable the cache will slow down the compilation speed of HMR. I believe we need to find a solution to solve this.

For the babel plugin include requirement, this is acceptable and we can note this in the documentation.

**Comment by chenjiahan** [comment]
I think now is a good time to start reviewing this PR. In addition, babel-plugin-vue-jsx-hmr is also suitable to be published as a separate npm package, so that other projects in the webpack and Rspack ecosystems can use it as well. What's your opinion on this?

**Comment by liyincode** [comment]
> I think now is a good time to start reviewing this PR. 😄
> 
> In addition, babel-plugin-vue-jsx-hmr is also suitable to be published as a separate npm package, so that other projects in the webpack and Rspack ecosystems can use it as well. What's your opinion on this?

Thank you for your affirmation! Submitting this plugin as an npm package is a very good idea! After I publish this plugin, I will replace the `babel-plugin-vue-jsx-hmr.ts` here with this npm package, and then submit a PR.(ง•_•)ง

**Comment by liyincode** [comment]
Hi, I have replaced it with a separate npm package [babel-plugin-vue-jsx-hmr](https://www.npmjs.com/package/babel-plugin-vue-jsx-hmr). and then here's my [PR](https://github.com/web-infra-dev/rsbuild/pull/2018)

please check😁

**Comment by chenjiahan** [comment]
Awesome! I will review the PR ASAP
