### ISSUE TITLE
[Feature]: rsbuild dev URL shoud respect dev.assetPrefix and rsbuild preview URL should respect output.assetPrefix

### ISSUE THREAD

**Issue by Alkaidcc** [web-infra-dev/rsbuild#2077]
### What problem does this feature solve?

When I set 
```
dev: {
    assetPrefix: '/test/'
},
```
command line output should be:
```shell

> rsbuild dev

  Rsbuild v0.6.0

  > Local:    http://localhost:3000/test/

```
but now missing `/test/`, it shows:

```shell
> rsbuild dev

  Rsbuild v0.6.0

  > Local:    http://localhost:3000/
```

Is it by design? Or did I misunderstand something

### What does the proposed API look like?

When I set `output.assetPrefix`, rsbuild preview should respect` output.assetPrefix` and same for `dev.assetPrefix` for rsbuild dev.

Has anything in rsbuild can implement the feature like [Vite base option](https://cn.vitejs.dev/config/shared-options#base)?

**Comment by xc2** [comment]
vite's base option looks like a good idea.

rsbuild's assetsPrefix is only for assets other than html files.

For html, please refer to:

- https://rsbuild.dev/config/source/entry
- https://rsbuild.dev/guide/basic/server#page-routing

Typically, naming an entry with something instead of 'index' will meet your need.

**Comment by Alkaidcc** [comment]
It seems that `output.distPath.html` is what I want, Thanks!
