### ISSUE TITLE
[Bug]: Rspack. Out. CssChunkFilename is doesn't work

### ISSUE THREAD

**Issue by dingjiang-gao** [web-infra-dev/rsbuild#2959]
### Version

```sh
"@rsbuild/core": "1.0.1-beta.3",
"@rsbuild/plugin-react": "1.0.1-beta.3",
mac Ventura 13.4 M1
```

### Details

    "@rsbuild/core": "1.0.1-beta.3",
    "@rsbuild/plugin-react": "1.0.1-beta.3",
版本如上，
配置rspack.out.CssChunkFilename 不起作用
配置如下
![image](https://github.com/user-attachments/assets/8e150d58-ec32-4dd5-a87c-0fc388c858a2)

在该版本下无打印

在0.6.8版本可有效果、且打印

![image](https://github.com/user-attachments/assets/1f00aea2-35f9-4e58-a27f-4043dc662342)

举一反三 应该cssAsync等也不起作用

### Reproduce link

xx

### Reproduce Steps

1: 使用rsbuild的相关版本
 "@rsbuild/core": "1.0.1-beta.3",
    "@rsbuild/plugin-react": "1.0.1-beta.3",
2: react项目
3: 配置
tools.rspack.output.filename.
        cssChunkFilename: (path) => {
          console.log('cssChunkFilename', path);

          return `[name][contenthash:8].css`;
        },

**Comment by chenjiahan** [comment]
Rsbuild >= v0.7 uses [CssExtractRspackPlugin](https://www.rspack.dev/plugins/rspack/css-extract-rspack-plugin) instead of Rspack's [experimental.css](https://www.rspack.dev/config/experiments#experimentscss), and `cssChunkFilename` only works with `experimental.css`.

See: https://rsbuild.dev/community/releases/v0-7#better-css-supports

You can use [tools.cssExtract.pluginOptions. chunkFilename](https://rsbuild.dev/config/tools/css-extract) instead.
