### ISSUE TITLE
[Bug]: @module-federation/runtime and @module-federation/sdk are included twice in the bundle

### ISSUE THREAD

**Issue by Verthon** [web-infra-dev/rsbuild#3805]
### Version

System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 75.72 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.59
    Safari: 17.6
  npmPackages:
    @rsbuild/core: ^1.0.8 => 1.0.17
    @rsbuild/plugin-react: ^1.0.5 => 1.0.5

### Details

Hello, not sure if this is intended but using simple remote with rsbuild:
```
moduleFederation: {
		options: {
			name: "my_remote",
			filename: "remoteEntry.js",
			exposes: {
				"./Button": "./src/Button.tsx",
			},
			shared: {
				react: {
					singleton: true,
					requiredVersion: pkg.dependencies["react"],
				},
				"react-dom": {
					singleton: true,
					requiredVersion: pkg.dependencies["react-dom"],
				},
			},
		},
	},
```

with dummy button
```tsx
export const Button = () => {
  return <button>I'm remote</button>
}
```

Makes remoteEntry.js huge - screen from the bundle-analyzer
![Image](https://github.com/user-attachments/assets/9fc66b94-d619-4fc6-b349-e3c1d4328e51)

### Reproduce link

https://github.com/Verthon/rsbuild-analyze/tree/main

### Reproduce Steps

1. cd remote
2. nvm use && npm i
3. npm run build:analyze
4. observe the bundle analyzer contents (it will open up automatically in browser)

**Comment by nyqykk** [comment]
@Verthon Sorry for the late response. The scenario in your question is the expected result.

1. When a project is transformed into an MF project, a `remoteEntry` will be produced. This is a complete entry that can be consumed by the host project. So having MF runtime within `remoteEntry` is normal.

2. This MF project is not only consumed by the host app but can also run independently because it is a single SPA(MAP) project. So MF runtime will be built into its main chunk to ensure independent running.

In both scenarios above, MF runtime will only be loaded once because they are two completely independent scenarios.

**Comment by Verthon** [comment]
Hello @nyqykk thank you very much for your explanation.
